In [1]:
pip install names

Requirement already satisfied: names in /Users/adrianrebmann/anaconda3/lib/python3.9/site-packages (0.3.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pandas==1.5.1

Requirement already satisfied: pandas==1.5.1 in /Users/adrianrebmann/anaconda3/lib/python3.9/site-packages (1.5.1)
Requirement already satisfied: numpy>=1.20.3 in /Users/adrianrebmann/anaconda3/lib/python3.9/site-packages (from pandas==1.5.1) (1.24.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/adrianrebmann/anaconda3/lib/python3.9/site-packages (from pandas==1.5.1) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/adrianrebmann/anaconda3/lib/python3.9/site-packages (from pandas==1.5.1) (2022.1)
Requirement already satisfied: six>=1.5 in /Users/adrianrebmann/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas==1.5.1) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import names
import random
import time
from datetime import datetime
import numpy as np
from random import randrange
from datetime import timedelta

In [4]:
#To generate initial timestamps

def random_date(start, end):
    delta = end - start
    int_delta = (delta.days * 24 * 60 * 60) + delta.seconds
    random_second = randrange(int_delta)
    return start + timedelta(seconds=random_second)

Create product table

In [5]:
# initialize data of lists.
product_types = {'PID': ['P1', 'P2', 'P3'],
        'Value': [15,10,20],
         'Fragile': [0,0,1]}

# Create DataFrame
product_types_df = pd.DataFrame(product_types)

# Print the output.
product_types_df

  PID  Value  Fragile
0  P1     15        0
1  P2     10        0
2  P3     20        1

Create customer table

In [6]:
customers_df = pd.DataFrame(columns = ["CID", "Name","Bank Account"])
for i in range(50):
    customers_df = customers_df.append({'CID':"c"+str(i+1),
                                        'Name':names.get_full_name(),
                                        'Bank Account': 'BE'+ str(68-i)+" " + str(7689-i*3)+" "  + str(4567+i*13+67)+" "  + str(3467 - i*7 -789)},
                                       ignore_index=True)
customers_df

/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/3148138654.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  customers_df = customers_df.append({'CID':"c"+str(i+1),

    CID               Name         Bank Account
0    c1      Rose Thompson  BE68 7689 4634 2678
1    c2         Lisa Muncy  BE67 7686 4647 2671
2    c3      Raymond Adams  BE66 7683 4660 2664
3    c4     Hilma Starrick  BE65 7680 4673 2657
4    c5     Marion Marenco  BE64 7677 4686 2650
5    c6         Fred Brown  BE63 7674 4699 2643
6    c7       Ronald Poole  BE62 7671 4712 2636
7    c8      Rusty Norrell  BE61 7668 4725 2629
8    c9      Joseph Morris  BE60 7665 4738 2622
9   c10    Joshua Scarlett  BE59 7662 4751 2615
10  c11         Mary Salas  BE58 7659 4764 2608
11  c12     Walter Wallace  BE57 7656 4777 2601
12  c13       Robert Keith  BE56 7653 4790 2594
13  c14       Latoya Brown  BE55 7650 4803 2587
14  c15     Robert Tunnell  BE54 7647 4816 2580
15  c16   Stephen Vizcarra  BE53 7644 4829 2573
16  c17     Claire Vanhorn  BE52 7641 4842 2566
17  c18         Lisa White  BE51 7638 4855 2559
18  c19  Thomas Batchelder  BE50 7635 4868 2552
19  c20        Martha Wada  BE49 7632 4881 2545
20  c21    Tiffany Lockett  BE48 7629 4894 2538
21  c22      Maria Sardina  BE47 7626 4907 2531
22  c23       Gina Vasquez  BE46 7623 4920 2524
23  c24  Robert Rottenberg  BE45 7620 4933 2517
24  c25      Delores Mccue  BE44 7617 4946 2510
25  c26  James Francescone  BE43 7614 4959 2503
26  c27       Jason Dziuba  BE42 7611 4972 2496
27  c28     Benjamin Smith  BE41 7608 4985 2489
28  c29         Jason Hurt  BE40 7605 4998 2482
29  c30   Rebecca Borowski  BE39 7602 5011 2475
30  c31        Kelly Anast  BE38 7599 5024 2468
31  c32    Michael Kaufman  BE37 7596 5037 2461
32  c33       Viola Bailey  BE36 7593 5050 2454
33  c34     Chris Northrop  BE35 7590 5063 2447
34  c35        Ethel Cotto  BE34 7587 5076 2440
35  c36    Donald Campbell  BE33 7584 5089 2433
36  c37     Lottie Fajardo  BE32 7581 5102 2426
37  c38  Patricia Williams  BE31 7578 5115 2419
38  c39        Arnold Cook  BE30 7575 5128 2412
39  c40      Julia Shibley  BE29 7572 5141 2405
40  c41      Marcus Miller  BE28 7569 5154 2398
41  c42        Mario Boehm  BE27 7566 5167 2391
42  c43      Hellen Osteen  BE26 7563 5180 2384
43  c44      Ann Henderson  BE25 7560 5193 2377
44  c45     Beverly Womack  BE24 7557 5206 2370
45  c46       Kelly Knight  BE23 7554 5219 2363
46  c47    Kassie Chappell  BE22 7551 5232 2356
47  c48      Michael Dolan  BE21 7548 5245 2349
48  c49        James Lewis  BE20 7545 5258 2342
49  c50       Carol Howard  BE19 7542 5271 2335

Create Order table

In [7]:
orders_df = pd.DataFrame(columns = ["OID","Quantity"])

Create the events table and the dynamic attribute tables

In [8]:
events_df = pd.DataFrame(columns = ["EID", "Activity","Timestamp",'Customer','Order',"Product Type","Resource"])
quantity_df = pd.DataFrame(columns = ["QID", "P1","P2",'P3',"EID","OID"])
order_value_df = pd.DataFrame(columns = ["VID", "Value","EID","OID"])
refund_df = pd.DataFrame(columns = ["RID", "Refund Value","EID","OID"])
shipping_method_df = pd.DataFrame(columns = ["SID", "Method","EID","OID"])

Create list of potential resources for each activity

In [9]:
#Resources1 are responsible for the activities: Receive order, confirm purchase, determine shipping method,
#sent invoice, recollect letter, pay refund, file order

Resources1= ['Jan','Gabriel','Olivia','Sophia','Evelyn','Noah']

#Resources 2 are responsible for the activities: Collect product, put protection around product, add product to package

Resources2 = ['Johannes','Elizabeth','Jack','Chloe','Sebastian','Grace']

#Resources 3 are responsible for the activities: Ship by courrier, Ship by mail, ship by express courrier, deliver package

Resources3 = ['Alexandre','Violet','David','Zoe','Ryan','Claire']

In [10]:
def choice_excluding(lst, exception):
    possible_choices = [v for v in lst if v != exception]
    return random.choice(possible_choices)
print(choice_excluding(Resources1,random.choice(Resources1)))

Olivia

Create first event

In [11]:
#Spare  with the idea of having the timestamps overlap
count = 1
Number_of_orders=2

resource1 = random.choice(Resources1)
resource2 = random.choice(Resources2)
resource3 = random.choice(Resources3)

start = datetime.strptime('1/1/2022 08:30 AM', '%d/%m/%Y %I:%M %p')
end =  datetime.strptime('1/1/2022 6:00 PM', '%d/%m/%Y %I:%M %p')

for i in range(0, Number_of_orders):
    #Initialize customers
    customer= customers_df.sample()
    CID=customer['CID'].values
    #Initialize products
    product = product_types_df.sample(n=3,replace=True)
    product_list = set(product.PID.values.tolist())
    print('product_list', product_list)

    #Initialize resources
    resource1 = choice_excluding(Resources1,resource1)
    resource2 = choice_excluding(Resources2,resource2)
    resource3 = choice_excluding(Resources3,resource3)

    print(start,end)

    stamp = random_date(start, end)

# Create first event

    #Events Table
    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Place Order',
                                    'Timestamp': stamp,
                                 'Customer': CID[0],
                                 'Order': 'o'+str(i+1),
                                 'Product Type': product_list},
                                           ignore_index=True)
    # Order Table
    orders_df=orders_df.append({'OID':'o'+str(i+1)},ignore_index=True)
    # Quantity Table
    quantity_df = quantity_df.append({'QID': 'Q' + str(i+1),'EID':"e"+str(i+count),'OID':'o'+str(i+1)},ignore_index=True)
    total = 0
    Quantity = []
    for q in range(0,3):
            quantity = random.randint(1, 4)
            Quantity.append(quantity)
            value = product.iloc[q]['Value']*quantity
            total = total + value
    product['Quantity'] = Quantity
    q_sum = product.groupby('PID').sum()
    print(q_sum)


    for value in product_list:
        quantity_df.at[i,value] = q_sum.at[value,'Quantity']


    # Refund Table
    refund_df = refund_df.append({'RID':'R'+ str(refund_df.shape[0] + 1), 'Refund Value' : 0,'EID':"e"+str(i+count),'OID':'o'+str(i+1)},ignore_index=True)

    # Increase count
    count = count + 1

    #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)



 # Create event 2

    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Receive Order',
                                    'Timestamp': stamp,
                                 'Customer': CID[0],
                                 'Order': 'o'+str(i+1),
                                 'Product Type': product_list,
                                 'Resource': resource1},
                                           ignore_index=True)
    # Increase count
    count = count + 1

    #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)

 # Create event 3

    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Confirm Purchase',
                                    'Timestamp': stamp,

                                 'Order': 'o'+str(i+1),
                                 'Product Type': product_list,
                                 'Resource': resource1},
                                           ignore_index=True)

    # Value Table (created by confirm purchase)

    order_value_df = order_value_df.append({'VID':'V'+str(i+1),'Value': total,'EID':"e"+str(i+count),'OID':'o'+str(i+1)},ignore_index=True)

    # Increase count
    count = count + 1

    #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)

 # Create event 4
    for value in product_list:
        events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Collect product from warehouse',
                                    'Timestamp': stamp,

                                 'Order': 'o'+str(i+1),
                                 'Product Type': set([value]),
                                 'Resource': resource2},
                                           ignore_index=True)
        # Increase count
        count = count + 1

       #Increase timestamp at random between 1 and 700 seconds
        time_duration = random.uniform(1,700)

        stamp = stamp + timedelta(seconds=time_duration)

 # Create event 5
    for value in product_list:
        fragile = product_types_df.loc[product_types_df['PID'] == value]['Fragile'].values
        if fragile[0] == 1:
            events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Put protection around the product',
                                    'Timestamp': stamp,

                                 'Order': 'o'+str(i+1),
                                 'Product Type': set([value]),
                                 'Resource': resource2},
                                           ignore_index=True)
            # Increase count
            count = count + 1

            #Increase timestamp at random between 1 and 700 seconds
            time_duration = random.uniform(1,700)

            stamp = stamp + timedelta(seconds=time_duration)

 # Create event 6
    for value in product_list:
        events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Add product to package',
                                    'Timestamp':  stamp,

                                 'Order': 'o'+str(i+1),
                                 'Product Type': set([value]),
                                 'Resource': resource2},
                                           ignore_index=True)
        # Increase count
        count = count + 1

        #Increase timestamp at random between 1 and 700 seconds
        time_duration = random.uniform(1,700)

        stamp = stamp + timedelta(seconds=time_duration)

# Create event 7
    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Get confirmation',
                                  'Timestamp': stamp,
                                 'Customer': CID[0],
                                 'Order': 'o'+str(i+1)},
                                           ignore_index=True)
    # Increase count
    count = count + 1

    #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)

# Create event 8
    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Confirm shipping information',
                                  'Timestamp': stamp,
                                 'Customer': CID[0],
                                 'Order': 'o'+str(i+1)},
                                           ignore_index=True)
    # Increase count
    count = count + 1

   #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)

# Create event 9
    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Determine shipping method',
                                  'Timestamp': stamp,
                                 'Product Type': product_list,
                                 'Order': 'o'+str(i+1),
                                 'Resource': resource1},
                                           ignore_index=True)
   # Increase count
    count = count + 1

   #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)

    #make the shipping method table

    #We need to parallelize therefore we make a split with random so either first the courrier is
    #send or first the invoice is send
    split = random.randint(0, 1)

    #Shipping method comes first

    if split==1:
        print('Shipping method comes first')
        #make event Determine shipping method and shipping method event itself
        control=0
        for value in product_list:
            fragile = product_types_df.loc[product_types_df['PID'] == value]['Fragile'].values
            if fragile[0] == 1:
                control = 1
                shipping_method_df = shipping_method_df.append({'EID':"e"+str(i+count-1),
                                                        'SID': 'S'+str(shipping_method_df.shape[0] + 1),
                                                        'Method': 'Courrier',
                                                        'OID':'o' + str(i+1)},
                                               ignore_index=True)

                #Add shipping event courrier

                now=datetime.now()
                events_df = events_df.append({'EID':"e"+str(i+count),
                                      'Activity':'Ship by courrier',
                                      'Timestamp': stamp,

                                     'Order': 'o'+str(i+1),
                                     'Resource': resource3},
                                               ignore_index=True)
                # Increase count
                count = count + 1

                #Increase timestamp at random between 1 and 700 seconds
                time_duration = random.uniform(1,700)

                stamp = stamp + timedelta(seconds=time_duration)

                break

        if order_value_df.loc[i]['Value'] >= 100 and control !=1 :
            control = 1
            shipping_method_df = shipping_method_df.append({'EID':"e"+str(i+count-1),
                                                        'SID': 'S' + str(shipping_method_df.shape[0] + 1),
                                                        'Method': 'Courrier',
                                                        'OID':'o' + str(i+1)},
                                                   ignore_index=True)
            #Add shipping event courrier
            now=datetime.now()
            events_df = events_df.append({'EID':"e"+str(i+count),
                                      'Activity':'Ship by courrier',
                                      'Timestamp': stamp,

                                     'Order': 'o'+str(i+1),
                                                         'Resource': resource3},
                                               ignore_index=True)
            # Increase count
            count = count + 1

            #Increase timestamp at random between 1 and 700 seconds
            time_duration = random.uniform(1,700)

            stamp = stamp + timedelta(seconds=time_duration)

        if control !=1:
            shipping_method_df = shipping_method_df.append({'EID':"e"+str(i+count-1),
                                                        'SID': 'S'+str(shipping_method_df.shape[0] + 1),
                                                        'Method': 'Mail',
                                                        'OID':'o' + str(i+1)},
                                                   ignore_index=True)
            #Add shipping event mail
            events_df = events_df.append({'EID':"e"+str(i+count),
                                      'Activity':'Ship by mail',
                                      'Timestamp': stamp,
                                     'Order': 'o'+str(i+1),
                                                         'Resource': resource3},
                                               ignore_index=True)
            # Increase count
            count = count + 1

            #Increase timestamp at random between 1 and 700 seconds
            time_duration = random.uniform(1,700)

            stamp = stamp + timedelta(seconds=time_duration)

        # Create event send invoice
        events_df = events_df.append({'EID':"e"+str(i+count),
                                      'Activity':'Send invoice',
                                      'Timestamp': stamp,
                                     'Order': 'o'+str(i+1),
                                     'Resource': resource1},
                                               ignore_index=True)
        # Increase count
        count = count + 1

        #Increase timestamp at random between 1 and 700 seconds
        time_duration = random.uniform(1,700)

        stamp = stamp + timedelta(seconds=time_duration)

    #Sent invoice comes first

    if split==0:
        print('Send invoice comes first')
         # Create event send invoice
        events_df = events_df.append({'EID':"e"+str(i+count),
                                      'Activity':'Send invoice',
                                      'Timestamp': stamp,
                                     'Order': 'o'+str(i+1),
                                     'Resource': resource1},
                                               ignore_index=True)
        # Increase count
        count = count + 1

        #Increase timestamp at random between 1 and 700 seconds
        time_duration = random.uniform(1,700)

        stamp = stamp + timedelta(seconds=time_duration)

        #make event Determine shipping method and shipping method event itself
        control=0
        for value in product_list:
            fragile = product_types_df.loc[product_types_df['PID'] == value]['Fragile'].values
            if fragile[0] == 1:
                control = 1
                shipping_method_df = shipping_method_df.append({'EID':"e"+str(i+count-2),
                                                        'SID': 'S'+str(shipping_method_df.shape[0] + 1),
                                                        'Method': 'Courrier',
                                                        'OID':'o' + str(i+1)},
                                               ignore_index=True)

                #Add shipping event courrier

                now=datetime.now()
                events_df = events_df.append({'EID':"e"+str(i+count),
                                      'Activity':'Ship by courrier',
                                      'Timestamp': stamp,

                                     'Order': 'o'+str(i+1),
                                     'Resource': resource3},
                                               ignore_index=True)
                # Increase count
                count = count + 1

               #Increase timestamp at random between 1 and 700 seconds
                time_duration = random.uniform(1,700)

                stamp = stamp + timedelta(seconds=time_duration)

                break

        if order_value_df.loc[i]['Value'] >= 100 and control !=1 :
            control = 1
            shipping_method_df = shipping_method_df.append({'EID':"e"+str(i+count-2),
                                                        'SID': 'S' + str(shipping_method_df.shape[0] + 1),
                                                        'Method': 'Courrier',
                                                        'OID':'o' + str(i+1)},
                                                   ignore_index=True)
            #Add shipping event courrier
            now=datetime.now()
            events_df = events_df.append({'EID':"e"+str(i+count),
                                      'Activity':'Ship by courrier',
                                      'Timestamp': stamp,

                                     'Order': 'o'+str(i+1),
                                                         'Resource': resource3},
                                               ignore_index=True)
            # Increase count
            count = count + 1

           #Increase timestamp at random between 1 and 700 seconds
            time_duration = random.uniform(1,700)

            stamp = stamp + timedelta(seconds=time_duration)

        if control !=1:
            shipping_method_df = shipping_method_df.append({'EID':"e"+str(i+count-2),
                                                        'SID': 'S'+str(shipping_method_df.shape[0] + 1),
                                                        'Method': 'Mail',
                                                        'OID':'o' + str(i+1)},
                                                   ignore_index=True)
            #Add shipping event mail
            now=datetime.now()
            events_df = events_df.append({'EID':"e"+str(i+count),
                                      'Activity':'Ship by mail',
                                      'Timestamp': stamp,
                                     'Order': 'o'+str(i+1),
                                                         'Resource': resource3},
                                               ignore_index=True)
            # Increase count
            count = count + 1


            #Increase timestamp at random between 1 and 700 seconds
            time_duration = random.uniform(1,700)

            stamp = stamp + timedelta(seconds=time_duration)

    # Create event deliver package
    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Deliver package',
                                  'Timestamp': stamp ,
                                 'Order': 'o'+str(i+1),
                                 'Customer':CID[0],
                                                     'Resource': resource3},
                                           ignore_index=True)

    # Increase count
    count = count + 1

    #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)

    # Create event Determine satisfaction
        #randomly decide on whether the customer wants a refund or not
    r = random.randint(0, 1)

    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Determine satisfaction',
                                  'Timestamp': stamp ,
                                 'Order': 'o'+str(i+1),
                                 'Customer':CID[0]},
                                           ignore_index=True)
    #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)

    if r==0:
        print('Customer does not want refund')
        count = count + 1
        events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'File Order',
                                  'Timestamp': stamp ,
                                 'Order': 'o'+str(i+1),
                                 'Resource': resource1
                                 },
                                           ignore_index=True)


        #Initialize the next timerange
        start = stamp - timedelta(seconds=10000)
        end = stamp

        continue

    #if no refund is asked the process ends with file order

    #create event File order
    else:
        refund_df = refund_df.append({'RID':'R' + str(refund_df.shape[0] + 1), 'Refund Value' : 1,'EID':"e"+str(i+count),'OID':'o'+str(i+1)},ignore_index=True)

        print('Since refund is asked, we take the other path')

     # Increase count
    count = count + 1

   #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)

    # Create event Request refund


    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Request refund',
                                  'Timestamp': stamp ,
                                 'Order': 'o'+str(i+1),
                                 'Customer':CID[0]},
                                           ignore_index=True)


    # Increase count
    count = count + 1

    #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)

    # Create event Confirm shipping information

    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Confirm shipping information',
                                  'Timestamp': stamp ,
                                 'Order': 'o'+str(i+1),
                                 'Customer':CID[0]},
                                           ignore_index=True)

    # Increase count
    count = count + 1

    #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)

    # Create event Determine shipping method

    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Determine shipping method',
                                  'Timestamp': stamp ,
                                 'Order': 'o'+str(i+1),
                                 'Resource': resource1},
                                           ignore_index=True)


    shipping_method_df = shipping_method_df.append({'EID':"e"+str(i+count),
                                                    'SID': 'S'+ str(shipping_method_df.shape[0] + 1),
                                                    'Method': 'Express Courrier',
                                                    'OID':'o' + str(i+1)},
                                               ignore_index=True)

   # Increase count
    count = count + 1

    #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)


    #We need to parallelize therefore we make a split with random so either first the express courrier is
    #send or first the recollect letter is send

    split = random.randint(0, 1)

    if split == 0:
            print('first express courrier then recollect letter')

            # Create event Ship by express courrier

            events_df = events_df.append({'EID':"e"+str(i+count),
                                          'Activity':'Ship by express courrier',
                                          'Timestamp': stamp ,
                                         'Order': 'o'+str(i+1),
                                                             'Resource': resource3},
                                                   ignore_index=True)




            # Increase count
            count = count + 1

            #Increase timestamp at random between 1 and 700 seconds
            time_duration = random.uniform(1,700)

            stamp = stamp + timedelta(seconds=time_duration)

            # Create event Recollect Letter

            events_df = events_df.append({'EID':"e"+str(i+count),
                                          'Activity':'Recollect Letter',
                                          'Timestamp': stamp ,
                                         'Order': 'o'+str(i+1),
                                         'Resource': resource1},
                                                   ignore_index=True)


            # Increase count
            count = count + 1

            #Increase timestamp at random between 1 and 700 seconds
            time_duration = random.uniform(1,700)

            stamp = stamp + timedelta(seconds=time_duration)

    if split == 1:
        print('first recollect letter then express courrier')

         # Create event Recollect Letter

        events_df = events_df.append({'EID':"e"+str(i+count),
                                      'Activity':'Recollect Letter',
                                      'Timestamp': stamp ,
                                     'Order': 'o'+str(i+1),
                                     'Resource': resource1},
                                               ignore_index=True)


        # Increase count
        count = count + 1

        #Increase timestamp at random between 1 and 700 seconds
        time_duration = random.uniform(1,700)

        stamp = stamp + timedelta(seconds=time_duration)

        # Create event Ship by express courrier

        events_df = events_df.append({'EID':"e"+str(i+count),
                                      'Activity':'Ship by express courrier',
                                      'Timestamp': stamp ,
                                     'Order': 'o'+str(i+1),
                                                         'Resource': resource3},
                                               ignore_index=True)

        # Increase count
        count = count + 1

        #Increase timestamp at random between 1 and 700 seconds
        time_duration = random.uniform(1,700)

        stamp = stamp + timedelta(seconds=time_duration)



    # Create event Return Package

    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Return Package',
                                  'Timestamp': stamp ,
                                 'Order': 'o'+str(i+1),
                                 'Customer': CID[0]},
                                           ignore_index=True)


    # Increase count
    count = count + 1

    #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)

     # Create event Pay refund

    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Pay refund',
                                  'Timestamp': stamp ,
                                 'Order': 'o'+str(i+1),
                                 'Customer': CID[0],
                                 'Resource': resource1},
                                           ignore_index=True)


    # Increase count
    count = count + 1

    #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)

    # Create event Deliver package

    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Deliver package',
                                  'Timestamp': stamp ,
                                 'Order': 'o'+str(i+1),
                                 'Customer': CID[0],
                                                     'Resource': resource3},
                                           ignore_index=True)


    # Increase count
    count = count + 1

   #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)

    #Create event Determine satisfaction

    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'Determine satisfaction',
                                  'Timestamp': stamp ,
                                 'Order': 'o'+str(i+1),
                                 'Customer':CID[0]},
                                           ignore_index=True)

    #Change refund variable to 0 since the customer is happy

    refund_df = refund_df.append({'RID':'R' + str(refund_df.shape[0] + 1), 'Refund Value' : 0,'EID':"e"+str(i+count),'OID':'o'+str(i+1)},ignore_index=True)


   # Increase count
    count = count + 1

    #Increase timestamp at random between 1 and 700 seconds
    time_duration = random.uniform(1,700)

    stamp = stamp + timedelta(seconds=time_duration)

    #Create event File Order

    events_df = events_df.append({'EID':"e"+str(i+count),
                                  'Activity':'File Order',
                                  'Timestamp': stamp ,
                                 'Order': 'o'+str(i+1),
                                 'Resource': resource1},
                                           ignore_index=True)


    #Initialize the next timerange
    start = stamp- timedelta(seconds=10000)
    end = stamp

product_list {'P1', 'P3'}
2022-01-01 08:30:00 2022-01-01 18:00:00
     Value  Fragile  Quantity
PID
P1      30        0         5
P3      20        1         4
Send invoice comes first
Since refund is asked, we take the other path
first express courrier then recollect letter
product_list {'P2', 'P1'}
2022-01-01 11:37:54.148389 2022-01-01 14:24:34.148389
     Value  Fragile  Quantity
PID
P1      30        0         5
P2      10        0         2
Shipping method comes first
Customer does not want refund

/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  orders_df=orders_df.append({'OID':'o'+str(i+1)},ignore_index=True)
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:43: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  quantity_df = quantity_df.append({'QID': 'Q' + str(i+1),'EID':"e"+str(i+count),'OID':'o'+str(i+1)},ignore_index=True)
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:61: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  refund_df = refund_df.append({'RID':'R'+ str(refund_df.shape[0] + 1), 'Refund Value' : 0,'EID':"e"+str(i+count),'OID':'o'+str(i+1)},ignore_index=True)
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:75: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:93: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:104: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  order_value_df = order_value_df.append({'VID':'V'+str(i+1),'Value': total,'EID':"e"+str(i+count),'OID':'o'+str(i+1)},ignore_index=True)
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:116: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:116: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:136: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:154: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:154: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:171: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:186: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:201: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:323: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:343: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  shipping_method_df = shipping_method_df.append({'EID':"e"+str(i+count-2),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:352: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:417: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:437: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:470: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  refund_df = refund_df.append({'RID':'R' + str(refund_df.shape[0] + 1), 'Refund Value' : 1,'EID':"e"+str(i+count),'OID':'o'+str(i+1)},ignore_index=True)
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:485: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:503: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:520: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:528: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  shipping_method_df = shipping_method_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:553: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:573: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:631: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:649: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:668: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:687: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:696: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  refund_df = refund_df.append({'RID':'R' + str(refund_df.shape[0] + 1), 'Refund Value' : 0,'EID':"e"+str(i+count),'OID':'o'+str(i+1)},ignore_index=True)
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:709: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  orders_df=orders_df.append({'OID':'o'+str(i+1)},ignore_index=True)
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:43: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  quantity_df = quantity_df.append({'QID': 'Q' + str(i+1),'EID':"e"+str(i+count),'OID':'o'+str(i+1)},ignore_index=True)
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:61: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  refund_df = refund_df.append({'RID':'R'+ str(refund_df.shape[0] + 1), 'Refund Value' : 0,'EID':"e"+str(i+count),'OID':'o'+str(i+1)},ignore_index=True)
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:75: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:93: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:104: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  order_value_df = order_value_df.append({'VID':'V'+str(i+1),'Value': total,'EID':"e"+str(i+count),'OID':'o'+str(i+1)},ignore_index=True)
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:116: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:116: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:154: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:154: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:171: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:186: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:201: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:283: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  shipping_method_df = shipping_method_df.append({'EID':"e"+str(i+count-1),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:289: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:304: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:417: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:437: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),
/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/4290215505.py:451: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  events_df = events_df.append({'EID':"e"+str(i+count),

Order the events by timestamps

In [12]:
#First order events by timestamps
events_df = pd.DataFrame(events_df)
events_df = events_df.sort_values(by=['Timestamp'])
#Reset the indexes
events_df= events_df.reset_index(drop=True)
events_df= events_df.reset_index()
#Rename column names
events_df=events_df.rename(columns = {'index':'EID_new', 'EID':'EID_old'})
#Rename the values of 'EID_new'
events_df['EID_new'] ='e' + events_df['EID_new'].astype(str)
events_df.head(50)

,EID_new,EID_old,Activity,Timestamp,Customer,Order,Product Type,Resource
0,e0,e1,Place Order,2022-01-01 12:04:28.000000,c2,o1,"{P1, P3}",NaN
1,e1,e2,Receive Order,2022-01-01 12:14:46.508022,c2,o1,"{P1, P3}",Gabriel
2,e2,e3,Confirm Purchase,2022-01-01 12:24:28.062087,NaN,o1,"{P1, P3}",Gabriel
3,e3,e4,Collect product from warehouse,2022-01-01 12:28:53.768985,NaN,o1,{P1},Elizabeth
4,e4,e5,Collect product from warehouse,2022-01-01 12:31:45.762037,NaN,o1,{P3},Elizabeth
5,e5,e6,Put protection around the product,2022-01-01 12:43:08.744235,NaN,o1,{P3},Elizabeth
6,e6,e7,Add product to package,2022-01-01 12:53:00.480865,NaN,o1,{P1},Elizabeth
7,e7,e8,Add product to package,2022-01-01 12:55:45.595417,NaN,o1,{P3},Elizabeth
8,e8,e9,Get confirmation,2022-01-01 13:04:45.951820,c2,o1,NaN,NaN
9,e9,e10,Confirm shipping information,2022-01-01 13:06:58.100942,c2,o1,NaN,NaN
10,e10,e11,Determine shipping method,2022-01-01 13:09:17.424369,NaN,o1,"{P1, P3}",Gabriel
11,e11,e12,Send invoice,2022-01-01 13:20:27.994901,NaN,o1,NaN,Gabriel
12,e12,e13,Ship by courrier,2022-01-01 13:29:26.177177,NaN,o1,NaN,Zoe
13,e13,e14,Deliver package,2022-01-01 13:30:37.419585,c2,o1,NaN,Zoe
14,e14,e15,Determine satisfaction,2022-01-01 13:35:54.818017,c2,o1,NaN,NaN
15,e15,e26,Place Order,2022-01-01 13:36:36.148389,c12,o2,"{P2, P1}",NaN
16,e16,e16,Request refund,2022-01-01 13:41:39.945886,c2,o1,NaN,NaN
17,e17,e27,Receive Order,2022-01-01 13:41:59.951474,c12,o2,"{P2, P1}",Sophia
18,e18,e17,Confirm shipping information,2022-01-01 13:42:00.123851,c2,o1,NaN,NaN
19,e19,e28,Confirm Purchase,2022-01-01 13:43:48.535779,NaN,o2,"{P2, P1}",Sophia
20,e20,e29,Collect product from warehouse,2022-01-01 13:43:54.747536,NaN,o2,{P2},Grace
21,e21,e30,Collect product from warehouse,2022-01-01 13:50:29.683263,NaN,o2,{P1},Grace
22,e22,e18,Determine shipping method,2022-01-01 13:50:39.368601,NaN,o1,NaN,Gabriel
23,e23,e31,Add product to package,2022-01-01 13:54:25.257332,NaN,o2,{P2},Grace
24,e24,e19,Ship by express courrier,2022-01-01 13:55:45.180187,NaN,o1,NaN,Zoe
25,e25,e20,Recollect Letter,2022-01-01 13:57:56.989620,NaN,o1,NaN,Gabriel
26,e26,e32,Add product to package,2022-01-01 14:04:20.433452,NaN,o2,{P1},Grace
27,e27,e21,Return Package,2022-01-01 14:09:20.038360,c2,o1,NaN,NaN
28,e28,e22,Pay refund,2022-01-01 14:09:50.843735,c2,o1,NaN,Gabriel
29,e29,e33,Get confirmation,2022-01-01 14:11:24.875522,c12,o2,NaN,NaN
30,e30,e23,Deliver package,2022-01-01 14:15:22.373136,c2,o1,NaN,Zoe
31,e31,e34,Confirm shipping information,2022-01-01 14:15:39.795596,c12,o2,NaN,NaN
32,e32,e24,Determine satisfaction,2022-01-01 14:19:22.040343,c2,o1,NaN,NaN
33,e33,e35,Determine shipping method,2022-01-01 14:24:19.667234,NaN,o2,"{P2, P1}",Sophia
34,e34,e25,File Order,2022-01-01 14:24:34.148389,NaN,o1,NaN,Gabriel
35,e35,e36,Ship by mail,2022-01-01 14:35:32.018307,NaN,o2,NaN,David
36,e36,e37,Send invoice,2022-01-01 14:40:27.904491,NaN,o2,NaN,Sophia
37,e37,e38,Deliver package,2022-01-01 14:48:52.703584,c12,o2,NaN,David
38,e38,e39,Determine satisfaction,2022-01-01 14:49:32.399199,c12,o2,NaN,NaN
39,e39,e40,File Order,2022-01-01 15:00:51.756482,NaN,o2,NaN,Sophia

In [13]:
#For every row in the dynamic attribute table
    #take the EID
    #look it up in the events_df table and retrieve the EID_new save it in a separate variable
    # put that value in the attributes table

for j in range(len(quantity_df)):
    ID = quantity_df.loc[j]['EID']
    quantity_df.loc[j]['EID'] = events_df['EID_new'].loc[events_df['EID_old'] == ID].values.tolist()[0]

for j in range(len(order_value_df)):
    ID = order_value_df.loc[j]['EID']
    order_value_df.loc[j]['EID'] = events_df['EID_new'].loc[events_df['EID_old'] == ID].values.tolist()[0]

for j in range(len(refund_df)):
    ID = refund_df.loc[j]['EID']
    refund_df.loc[j]['EID'] = events_df['EID_new'].loc[events_df['EID_old'] == ID].values.tolist()[0]

for j in range(len(shipping_method_df)):
    ID = shipping_method_df.loc[j]['EID']
    shipping_method_df.loc[j]['EID'] = events_df['EID_new'].loc[events_df['EID_old'] == ID].values.tolist()[0]

events_df= events_df.drop(['EID_old'], axis=1)
events_df.rename(columns = {'EID_new':'EID'}, inplace = True)

FIX QUANTITY TABLE

In [14]:
quantity_df[['P1','P2','P3']] =  quantity_df[['P1','P2','P3']].fillna(0)
quantity_df['Quantity']=quantity_df[['P1','P2','P3']].values.tolist()
quantity_df=quantity_df.drop(['P1','P2','P3'], axis=1)
columns_titles = ["QID","Quantity",'EID','OID']
quantity_df=quantity_df.reindex(columns=columns_titles)
quantity_df

  QID   Quantity  EID OID
0  Q1  [5, 0, 4]   e0  o1
1  Q2  [5, 2, 0]  e15  o2

In [15]:
orders_df["Quantity"]= quantity_df['Quantity']

In [16]:
orders_df

  OID   Quantity
0  o1  [5, 0, 4]
1  o2  [5, 2, 0]

In [17]:
product_types_df

  PID  Value  Fragile
0  P1     15        0
1  P2     10        0
2  P3     20        1

In [18]:
customers_df

    CID               Name         Bank Account
0    c1      Rose Thompson  BE68 7689 4634 2678
1    c2         Lisa Muncy  BE67 7686 4647 2671
2    c3      Raymond Adams  BE66 7683 4660 2664
3    c4     Hilma Starrick  BE65 7680 4673 2657
4    c5     Marion Marenco  BE64 7677 4686 2650
5    c6         Fred Brown  BE63 7674 4699 2643
6    c7       Ronald Poole  BE62 7671 4712 2636
7    c8      Rusty Norrell  BE61 7668 4725 2629
8    c9      Joseph Morris  BE60 7665 4738 2622
9   c10    Joshua Scarlett  BE59 7662 4751 2615
10  c11         Mary Salas  BE58 7659 4764 2608
11  c12     Walter Wallace  BE57 7656 4777 2601
12  c13       Robert Keith  BE56 7653 4790 2594
13  c14       Latoya Brown  BE55 7650 4803 2587
14  c15     Robert Tunnell  BE54 7647 4816 2580
15  c16   Stephen Vizcarra  BE53 7644 4829 2573
16  c17     Claire Vanhorn  BE52 7641 4842 2566
17  c18         Lisa White  BE51 7638 4855 2559
18  c19  Thomas Batchelder  BE50 7635 4868 2552
19  c20        Martha Wada  BE49 7632 4881 2545
20  c21    Tiffany Lockett  BE48 7629 4894 2538
21  c22      Maria Sardina  BE47 7626 4907 2531
22  c23       Gina Vasquez  BE46 7623 4920 2524
23  c24  Robert Rottenberg  BE45 7620 4933 2517
24  c25      Delores Mccue  BE44 7617 4946 2510
25  c26  James Francescone  BE43 7614 4959 2503
26  c27       Jason Dziuba  BE42 7611 4972 2496
27  c28     Benjamin Smith  BE41 7608 4985 2489
28  c29         Jason Hurt  BE40 7605 4998 2482
29  c30   Rebecca Borowski  BE39 7602 5011 2475
30  c31        Kelly Anast  BE38 7599 5024 2468
31  c32    Michael Kaufman  BE37 7596 5037 2461
32  c33       Viola Bailey  BE36 7593 5050 2454
33  c34     Chris Northrop  BE35 7590 5063 2447
34  c35        Ethel Cotto  BE34 7587 5076 2440
35  c36    Donald Campbell  BE33 7584 5089 2433
36  c37     Lottie Fajardo  BE32 7581 5102 2426
37  c38  Patricia Williams  BE31 7578 5115 2419
38  c39        Arnold Cook  BE30 7575 5128 2412
39  c40      Julia Shibley  BE29 7572 5141 2405
40  c41      Marcus Miller  BE28 7569 5154 2398
41  c42        Mario Boehm  BE27 7566 5167 2391
42  c43      Hellen Osteen  BE26 7563 5180 2384
43  c44      Ann Henderson  BE25 7560 5193 2377
44  c45     Beverly Womack  BE24 7557 5206 2370
45  c46       Kelly Knight  BE23 7554 5219 2363
46  c47    Kassie Chappell  BE22 7551 5232 2356
47  c48      Michael Dolan  BE21 7548 5245 2349
48  c49        James Lewis  BE20 7545 5258 2342
49  c50       Carol Howard  BE19 7542 5271 2335

In [19]:
orders_df

  OID   Quantity
0  o1  [5, 0, 4]
1  o2  [5, 2, 0]

In [20]:
quantity_df

  QID   Quantity  EID OID
0  Q1  [5, 0, 4]   e0  o1
1  Q2  [5, 2, 0]  e15  o2

In [21]:
order_value_df

  VID Value  EID OID
0  V1   155   e2  o1
1  V2    95  e19  o2

In [22]:
refund_df

  RID Refund Value  EID OID
0  R1            0   e0  o1
1  R2            1  e14  o1
2  R3            0  e32  o1
3  R4            0  e15  o2

In [23]:
shipping_method_df

  SID            Method  EID OID
0  S1          Courrier  e10  o1
1  S2  Express Courrier  e22  o1
2  S3              Mail  e33  o2

In [24]:
writer = pd.ExcelWriter('DOCEL_log_2.xlsx', engine='xlsxwriter')

In [25]:
# event table
events_df.to_excel(writer, sheet_name='Events')

#object tables
customers_df.to_excel(writer, sheet_name='Customer')
product_types_df.to_excel(writer, sheet_name='Product Type')
orders_df.to_excel(writer, sheet_name='Order')

#Attribute tables
#quantity_df.to_excel(writer, sheet_name='Quantity')
order_value_df.to_excel(writer, sheet_name='Value')
refund_df.to_excel(writer, sheet_name='Refund Value')
shipping_method_df.to_excel(writer, sheet_name='Method')

In [26]:
# Close the Pandas Excel writer and output the Excel file.
writer.save()

/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11964/1744656341.py:2: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()

In [27]:
#OCEL LOG

In [28]:
#OCEL = pd.merge(, quantity_df, how="left",on='EID')
OCEL = pd.merge(events_df, order_value_df, how="left",on='EID')
OCEL = pd.merge(OCEL, refund_df, how="left",on='EID')
OCEL = pd.merge(OCEL, shipping_method_df, how="left",on='EID')

OCEL=OCEL.fillna('/')
OCEL=OCEL.drop([OID_x','OID_y','VID','RID','SID'], axis=1)
OCEL

KeyError: "['QID'] not found in axis"

In [ ]:
writer = pd.ExcelWriter('OCEL_log_2.xlsx', engine='xlsxwriter')

In [ ]:
# event table
OCEL.to_excel(writer, sheet_name='Events')

#object tables
customers_df.to_excel(writer, sheet_name='Customer')
product_types_df.to_excel(writer, sheet_name='Product Type')
orders_df.to_excel(writer, sheet_name='Order')

In [ ]:
# Close the Pandas Excel writer and output the Excel file.
writer.save()

/var/folders/3b/7cjmdk4d3ysg59q40b__n0mm0000gn/T/ipykernel_11579/1744656341.py:2: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()